version: '3.8'

services:
  app:
    image: node:18
    container_name: shopper-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'